FORMAT: 1A

# HomeShop

HomeShop is an application to automatize your groceries needs, and to help you spend less time shopping.

## Supermarkets Collection [/markets]

### List All Markets [GET]
TODO: order by next, and latest used

Returns a list of supermarkets, with links to their images.

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Extra",
                "image": "../imgs/markets/extra.png",
                "products": "/markets/1/products"
            },
            {
                "id": 2,
                "name": "Carrefour",
                "image": "../imgs/markets/carrefour.png",
                "products": "/markets/2/products"
            },
            {
                "id": 3,
                "name": "Bretas",
                "image": "../imgs/markets/bretas.png",
                "products": "/markets/3/products"
            },
            {
                "id": 4,
                "name": "Pão de açucar",
                "image": "../imgs/markets/pao_de_acucar.png",
                "products": "/markets/4/products"
            },
            {
                "id": 5,
                "name": "Barão",
                "image": "../imgs/markets/barao.png",
                "products": "/markets/5/products"
            }
        ]
            
### Register a new Supermarket [POST]

Registers a new supermarket to make transactions on, with the base image and everything else to be used.

Base64 images shortened, because apiary would complain otherwise.

+ Request (application/json)

        {
            "name": "Pão de Açucar",
            "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gAMQXBwbGVN",
            "location": {
                "lat": "37.7898",
                "lon": "-122.3942"
            }
        }

+ Response 201 (application/json)

    + Headers

            Location: /markets/5

    + Body

            {
                "id": 5,
                "name": "Pão de Açucar",
                "image": "../imgs/markets/bretas.png",
                "products": "/markets/5/products"
            }

## Single Market [/markets/{market_id}]

References each market, with more information about them, including links to the products and other functionalities.

+ Parameters
    + market_id (number) - ID of the Market in the form of an integer

### Market Detail [GET]

Returns more information about one supermarket, with links to more actions.

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Extra",
            "header": "base64:/imgs/markets/extra-header.png",
            "products": "/markets/1/products"
        }

# Group Products

All the operations related to the products go here.

## Products Collection [markets/{market_id}/products]

References one collection of products from a single supermarket.

+ Parameters
    + market_id (number) - ID of the Market in the form of an integer

### Create a New Product on this supermarket [POST]

Creates a new product with a POST request.

+ Request (application/json)

        {
            "name": "Sucrilhos",
            "description": "They are yummy.",
            "price": "R$45,00",
            "current-stock": 45,
            "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gAMQXBwbGVN="
        }

+ Response 201 (application/json)

    + Headers

            Location: /markets/1/products/2

    + Body

            {
                "name": "Sucrilhos",
                "description": "They are yummy.",
                "price": "R$45,00",
                "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gAMQXBwbGVN="
            }

### Get all products for this supermarket, with filtering and pagination [GET]

## Products Collection [markets/{market_id}/products/{product_id}]

### Alter one product [POST]

### Delete one product [DELETE]

## Login [/login/{email}/{password}]