FORMAT: 1A
HOST: http://private-3c4e5-homeshop.apiary-mock.com

# HomeShop

HomeShop is an application to automatize your groceries needs, and to help you spend less time shopping.

## Login [/login]

Handles the login.

### Handles login [POST]

Handles the login of a previous user. Should be sent over SSL.

+ Request (application/json)

        {
            "email": "yuri-m-dias",
            "senha": "senha123"
        }

+ Response 200 (application/json)

    + Body

            {
                "auth-token": "tk_GmVtYvffWZM7D721iO4mFiXI1ywlDWsTyFQU"
            }

+ Response 422 (application/json)

    + Body

            {
                "error": "Failed to authenticate. Wrong username or password."
            }

+ Response 500 (application/json)

    + Body

            {
                "error": "Internal server error."
            }

# Group markets information

## Supermarkets Collection [/markets]

### List All Markets [GET]
TODO: order by next, and latest used

Returns a list of supermarkets, with links to their images.

+ Response 200 (application/json)

        [
            {
                "id": 1,
                "name": "Extra",
                "image": "http://seeklogo.com/images/E/Extra_Hipermercados-logo-823612EED1-seeklogo.com.gif",
                "products": "/markets/1/products"
            },
            {
                "id": 2,
                "name": "Carrefour",
                "image": "http://i0.wp.com/logobr.org/wp-content/uploads/2009/10/Carrefour.jpg?zoom=1.5&fit=420%2C276",
                "products": "/markets/2/products"
            },
            {
                "id": 3,
                "name": "Bretas",
                "image": "http://seeklogo.com/images/B/bretas-supermercado-logo-FFE5262213-seeklogo.com.gif",
                "products": "/markets/3/products"
            },
            {
                "id": 4,
                "name": "Pão de açucar",
                "image": "http://seeklogo.com/images/P/pao-de-acucar-logo-F0493D0EE0-seeklogo.com.png",
                "products": "/markets/4/products"
            },
            {
                "id": 5,
                "name": "Barão",
                "image": "https://fbcdn-profile-a.akamaihd.net/hprofile-ak-xtf1/v/t1.0-1/13600215_931286913684033_748324593895396071_n.png?oh=134026ebf8ec8a4f90c75b5153702dd3&oe=5828E7A2&__gda__=1479272331_eb1f06d72560a7df56b4102191ca0661",
                "products": "/markets/5/products"
            }
        ]

## Single Market [/markets/{market_id}]

References each market, with more information about them, including links to the products and other functionalities.

+ Parameters
    + market_id (number) - ID of the Market in the form of an integer

### Market Detail [GET]

Returns more information about one supermarket, with links to more actions.

+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Extra",
            "header": "base64:/imgs/markets/extra-header.png",
            "products": "/markets/1/products",
            "location": {
                "lat": "37.7898",
                "lon": "-122.3942"
            }
        }

# Group Products information

All the operations related to the products go here.

## Products Collection [/markets/{market_id}/products{?start,limit}]

References one collection of products from a single supermarket.

+ Parameters
    + market_id (number) - ID of the Market in the form of an integer
    + start (number) - number of the starting element, if paging
    + limit (number) - limits the requet to this many elements

### Get all products for this supermarket, with filtering and pagination [GET]
TODO: filtering and sorting

+ Response 200 (application/json)

        {
            "market": "Extra",
            "meta": {
                "page": 1,
                "start": 0,
                "limit": 20
            },
            "products": [
                {
                    "id": 1,
                    "name": "Sucrilhos",
                    "description": "Yummy!",
                    "price": "R$53,00",
                    "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gAMQXBwbGVN="
                },
                {
                    "id": 2,
                    "name": "Sucrilhos2",
                    "description": "Yummy2!",
                    "price": "R$54,00",
                    "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gAMQXBwbGVN="
                },
                {
                    "id": 3,
                    "name": "Sucrilhos3",
                    "description": "Yummy!3",
                    "price": "R$33,00",
                    "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gAMQXBwbGVN="
                }
            ]
        }

## Product detail [/markets/{market_id}/products/{product_id}]

References one product from a market.

+ Parameters
    + market_id (number) - ID of the Market in the form of an integer
    + product_id (number) - ID of the Product in the form of an integer

### Detail one product [GET]

+ Response 200 (application/json)

    + Body

            {
                "name": "Sucrilhos",
                "description": "They are yummy.",
                "price": "R$45,00",
                "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gAMQXBwbGVN="
            }

### Alter one product [POST]

+ Response 200 (application/json)

### Delete one product [DELETE]

+ Response 200 (application/json)

# Group User Operations

## User detail [/users/{user_id}]

Retrieves user information.

+ Parameters
    + user_id (number) - ID of the User in the form of an integer

### Information of an User [GET]

+ Response 200 (application/json)

    + Body

            {
                "nome": "Leopoldo Magalhães",
                "email": "leopoldo@gmail.com",
                "cpf":"111.222.333-44",
                "endereco": "Rua Leopoldo Magalhães Qd 44 Lt 67",
                "numeroCartao": "************1234"
            }

### Alter user information [POST]

+ Request (application/json)

        {
            "nome": "Leopoldo Magalhães",
            "email": "leopoldo@gmail.com",
            "cpf":"111.222.333-44",
            "endereco": "Rua Leopoldo Magalhães Qd 44 Lt 67",
            "numeroCartao": "3879.2736.3512.1234"
        }

+ Response 200 (application/json)

## User Register [/user]

Register an User

###Register an User [PUT]
+ Request (application/json)

        {
            "name": "Leopoldo Magalhães",
            "email": "leopoldo@gmail.com",
            "cpf":"111.222.333-44",
            "endereco": "Rua Leopoldo Magalhães Qd 44 Lt 67",
            "cartao": "24526231234"
        }

+ Response 200 (application/json)

    + Body

            {
                "status": "Success"
            }

+ Response 500 (application/json)

    + Body

            {
                "status": "Error while trying to register an user"
            }

+ Response 409 (application/json)

    + Body

            {
                "status": "Conflict: Email already registered"
            }

## Credit Card Operations [/users/{user_id}/creditcard]

Operations of on user's credit cards.

+ Parameters
    + user_id (number) - ID of the User in the form of an integer

### Register a credit card [PUT]

+ Request (application/json)

        {
            "name": "LEOPOLDO MAGALHAES",
            "number": "1111222233334444",
            "cvs":"123",
            "date": "11/2020",
            "brand": "visa"
        }

+ Response 200 (application/json)


### Alter card information [POST]

+ Request (application/json)

        {
            "name": "LEOPOLDO MAGALHAES",
            "number": "1111222233334444",
            "cvs":"231",
            "date": "11/2020",
            "brand": "mastercard"
        }

+ Response 200 (application/json)

### Delete credit card [DELETE]

+ Request (application/json)

        {
            "card_number": "1111222233334444"
        }

+ Response 200 (aplicaion/json)


# Group Cart and history

## Collection Cart current [/users/{user_id}/cart]

The cart for the user specified.

+ Parameters
    + user_id (number) - ID of the User in the form of an integer

### Detail the cart collection [GET]

+ Request (application/json)

        {
            "id": 1
        }

+ Response 200 (application/json)

    + Body

            {
                "products": [
                    {
                        "id": 1,
                        "name": "Sucrilhos",
                        "description": "Yummy!",
                        "price": "R$53,00",
                        "quantity": 3
                        "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gAMQXBwbGVN="
                    },
                    {
                        "id": 2,
                        "name": "Omo",
                        "description": "Sabão em pó ação total",
                        "price": "R$8,00",
                        "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gAMQXBwbGVN="
                    },
                    {
                        "id": 3,
                        "name": "Arroz Cristal",
                        "description": "Pureza em forma de grãos",
                        "price": "R$13,00",
                        "image": "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEASABIAAD//gAMQXBwbGVN="
                    }
                ]
            }

+ Request (application/json)

        {
            "id": 2
        }

+ Response 404 (application/json)

    + Body

            {
                "error": "Empty cart"
            }
### Alters a product from cart [POST]

+ Response 200 (application/json)

    + Body

            {
                "status": "Success"
            }

### Adds a product to cart [PUT]

+ Response 200 (application/json)

    + Body

            {
                "status": "Success"
            }

### Delete one product from cart [DELETE]

+ Response 200 (application/json)

## Collection Cart history [/users/{user_id}/buyHistory{?market_id}]

References the collection of all previous carts, for a specific user, and a market.

+ Parameters
    + user_id (number) - ID of the User in the form of an integer

### Get the collection [GET]

+ Parameters

    + market_id (number, optional) - ID of the Market in the form of an integer

+ Response 200 (application/json)

        {
                "meta": {
                        "page": 1,
                        "start": 0,
                        "limit": 20
                },
                "history": [
                    {
                        "id": 14,
                        "market": "Extra",
                        "total": "R$54,00",
                        "date": 1466209329
                    },
                    {
                        "id": 24,
                        "market": "Marcos",
                        "total": "R$87,92",
                        "date": 1466209330
                    },
                    {
                        "id": 39,
                        "market": "Extra",
                        "total": "R$11,23",
                        "date": 1466209331
                    }
                ]
        }

+ Response 200 (application/json)

        {
                "meta": {
                        "page": 1,
                        "start": 0,
                        "limit": 20
                },
                "market": "Extra",
                "history": [
                    {
                        "id": 1,
                        "total": "R$54,00",
                        "date": 1466209329
                    },
                    {
                        "id": 2,
                        "total": "R$87,92",
                        "date": 1466209330
                    },
                    {
                        "id": 3,
                        "total": "R$11,23",
                        "date": 1466209331
                    }
                ]
        }

## User Cart History [/users/{user_id}/buyHistory/{history_id}]

References the a single history for that user.

+ Parameters
    + user_id (number) - ID of the User in the form of an integer
    + history_id (number) - ID of the History found, in the form of an integer

### Gets the history [GET]

+ Response 200 (application/json)

        {
                "meta": {
                        "page": 1,
                        "start": 0,
                        "limit": 20
                },
                "market": "Extra",
                "date": 1466209329,
                "total": "R$54,00",
                "products": [
                    {
                        "id": 14,
                        "quantity": 5,
                        "unitaryPrice": "R$5,12",
                        "totalUnitary": "R$25,60"
                    },
                    {
                        "id": 16,
                        "quantity": 1,
                        "unitaryPrice": "R$5,11",
                        "totalUnitary": "R$25,00"
                    },
                    {
                        "id": 18,
                        "quantity": 2,
                        "unitaryPrice": "R$5,12",
                        "totalUnitary": "R$25,60"
                    }
                ]
        }